<?php 
$this->dojo()
	->enable()
	->requireModule(array(
		'dojox.widget.Dialog',
		'dijit.form.Form',
		'dojox.form.BusyButton',
		'dijit.form.NumberSpinner',
	));
$this->dojo()->onLoadCaptureStart();
?>
function(){
	var nodes = dojo.query('.orderButton');
	nodes.connect('onclick','makeOrder');
}
<?php $this->dojo()->onLoadCaptureEnd();?>
<?php $this->partialLoop()->setObjectKey('product');?>
<?=$this->partialLoop('./product-index/item-partial.phtml',$this->products)?>