<?php
$product = $this->product;
$thumbHelper = $this->thumbnail();
$thumbUrl = $thumbHelper->url(array('group'=>'products','iid'=>$product->id,'size'=>'small'));
if ($thumbHelper->isExist($thumbUrl)) {
	$dim = $thumbHelper->getDimensions($thumbUrl);
	$isHorizontal = $dim['isHorizontal'];
} else {
	$isHorizontal = true;
}
?>
<div class="itemRoundLightGrayBox">
	<img class="lightGrayBorder" src="<?=$thumbUrl?>" <?=( ($isHorizontal) ? 'width="148px" height="104px"' : 'width="104px" height="148px"' )?> />
	<div class="productDesc">
    	<h2><?=$product->name?></h2>
    	<span class="desc"><?=$product->description?></span>
    	<div class="price">
        	<div <?=(($product->sale_price) ? 'class="notSale"' : null)?>>ราคาปกติ<span><?=$product->price?></span>บาท</div>
    	<?php if($product->sale_price) :?>
            <div class="sale">ราคาพิเศษ<span><?=$product->sale_price?></span>บาท</div>
      	<?php endif;?>
            <span class="orderButton" params="{url:'<?=$this->url(array('controller'=>'cart-index','action'=>'ajax-form','module'=>'shop','format'=>'html','name'=>'order','id'=>$product->rowid),null,true)?>'}"></span>
           	<a href="<?=$this->url(array('action'=>'view','controller'=>'product-index','module'=>'shop','id'=>$product->rowid),null,true)?>" class="infoButton"></a>
    	</div>
	</div>
</div>	