<?php 
$product = $this->product;

$this->dojo()
	->enable()
	->requireModule(array(
		'dojox.widget.Dialog',
		'dijit.form.Form',
		'dojox.form.BusyButton',
		'dijit.form.NumberSpinner',
	));

$this->dojo()->onLoadCaptureStart();
?>
function(){
	var nodes = dojo.query('.orderButton');
	nodes.connect('onclick','makeOrder');
}
<?php $this->dojo()->onLoadCaptureEnd();?>
<?=$this->partial('./product-index/item-partial.phtml',array('product'=>$product))?>
<div id="detailContent">
	<?=$product->content?>
</div>
