<?php 
$currency = Zend_Registry::get('Zend_Currency');
$date = new Zend_Date();

$order = $this->order;
?>
<dl class="itemRoundLightGrayBox">
	<dt>เลขที่ใบสั่งซื้อ</dt>
	<dd><?=$order->id?></dd>
	<dt>วันที่สั่งซื้อ</dt>
	<dd><?=$date->set($this->order->order_date)->get(Zend_Date::DATETIME_MEDIUM)?></dd>
	<dt>ชื่อผู้รับสินค้า</dt>
	<dd><?=$order->shipping_name?></dd>
	<dt style="height:50px">ที่อยู่จัดส่ง</dt>
	<dd>
	<?=$this->address(array(
		'address'=>$order->shipping_address,
		'subdistrict'=>$order->shipping_subdistrict,
		'district'	=>	$order->shipping_district,
		'province_code'	=>	$order->shipping_province_code,
		'zipcode'	=>	$order->shipping_zipcode,
	))?>
	</dd>
</dl>
<h2>รายการสั่งซื้อสินค้า</h2>
	<table id="cartPO">
		<tr>
			<th>รหัสสินค้า</th>
			<th>รายการ</th>
			<th>ราคาต่อหน่วย (<?=$currency->getName()?>)</th>
			<th>จำนวน</th>
			<th>ราคารวม (<?=$currency->getName()?>)</th>
		</tr>
		<?php foreach ($order->items as $item) :?>
		<tr>
			<td><?=$item->code?></td>
			<td><?=$item->name?></td>
			<td><?=$currency->toCurrency($item->unit_price,array('display'=>Zend_Currency::NO_SYMBOL))?></td>
			<td><?=$currency->toCurrency($item->quantity,array('display'=>Zend_Currency::NO_SYMBOL))?></td>
			<td><?=$currency->toCurrency($item->unit_total_price,array('display'=>Zend_Currency::NO_SYMBOL))?></td>
		</tr>
		<?php endforeach;?>
		<tr>
			<td colspan="4">ยอดรวมทั้งหมด (<?=$currency->getName()?>)</td>
			<td><?=$currency->toCurrency($this->order->total_price,array('display'=>Zend_Currency::NO_SYMBOL))?></td>
		</tr>
	</table>
