<ul id="viewList">
<?php foreach ($this->fields as $field):?>
	<?php 
	$name = $field['name'];
	$label = $field['label'];
	$value = $field['value'];
	$options = $field['options'];
	$readonly = $options['readonly'];
	$wyciwyg = $options['wyciwyg'];
	$controller = $options['controller'];
	$object = $this->object;
	
	if (!$readonly) {
		$urlOptions = array('action'=>'ajax-form','name'=>$name,'id'=>$object->id,'format'=>'html');
			
		if (!empty($controller)) {
		    $urlOptions['controller'] = $controller;
		}
		
		$params = array('url'=>$this->url($urlOptions));
		$params['options'] = array();
		if (is_array($options)) {
		    $params['options']['wyciwyg'] = $wyciwyg;
		}
		$jsonParams = Zend_Json_Encoder::encode($params);
	} else {
	    $jsonParams = null;
	}
	?>
	<li class="item">
		<dl class="title <?=( $readonly?'readonly':'editable' )?>" field="<?=$name?>" params=<?=$jsonParams?>>
			<dt class="label"><?=$field['label']?></dt>
			<dd class="value-element">
				<value class="<?=( !empty($field['valueClass']) ? $field['valueClass']:null )?>">
					<?php 
					if (!empty($value)) {
					    if (is_a($value, 'Doctrine_Collection')) {
					        if ($value->count()) {
					            echo '<ul class="sublist">';
					            foreach ($value as $value1):
					            	$module = array();
					            	$module['value'] = $value1;
					            	$module['options'] = $options;
					            ?>
					            	<?=$this->partial('view-sublist-partial.phtml',$module)?>
					            <?php 
					            endforeach;
					            echo '</ul>';
					        } else {
					            echo '<span class="grayOut">ไม่ระบุ</span>';
					        }
					    } else { 
					        echo $value; 
					    }
					} else {
					    echo '<span class="grayOut">ไม่ระบุ</span>';
					}
					?>
				</value>
			<?php if (!$readonly) :?>
				<span class="async icon color1C92B7 editIcon"></span>
				<img class="loader" src="/images/ajax-loader1.gif" />
			<?php endif;?>
			</dd>
		</dl>
		<div class="editor"></div>
	</li>
<?php endforeach;?>
</ul>