<?php 
$this->dojo()
	->enable()
	->requireModule(array(
		'dijit.form.Form',
		'dijit.form.TextBox',
		'dijit.form.ValidationTextBox',
		'dijit.form.Select',
		'dijit.form.FilteringSelect',
		'dijit.form.DateTextBox',
		'dijit.form.Textarea',
		'dijit.form.RadioButton',
		'dijit.form.Button',
		'dojox.form.BusyButton',
		'dojox.validate',
		'dojox.validate.web',
		'dojo.NodeList-traverse',
		'dojox.widget.Dialog',
	));
$this->dojo()->onLoadCaptureStart();
?>
function() {
	dojo.query('.deleleOp').connect('onclick','deleteUserItem');
	dojo.query('#resultTable .item').connect('onclick','viewUserItem');
}
<?php $this->dojo()->onLoadCaptureEnd();?>
<div id="leftContent">
	<div id="leftMenuTitle">
		<span class="label">จัดการผู้ใช้</span>
		<span class="icon colorE9E9E9 usersIcon"></span>
	</div>
	<div id="leftMenu">
		<?php echo $this->navigation()->menu(); ?>
	</div>
</div>

<div id="centerContentContainer">
	<div id="centerContent">
	<div id="searchResultLabel">ผลการค้นหาพบทั้งหมด <?=Zend_Locale_Format::toNumber($this->users->count())?> รายการ</div>
	<table id="resultTable">
		<tr>
			<th style="width:100px">หมายเลขผู้ใช้</th>
			<th>ชื่อ-สกุล</th>
		</tr>
		<?php foreach ($this->users as $user):?>
			<tr class="item" params="{url:'<?=$this->url(array('action'=>'view','item'=>$user->id,'format'=>'html'))?>'}">
				<td><?=$user->id?></td>
				<td><?=$user->first_name?> <?=$user->last_name?><span class="deleleOp async icon color1C92B7 closeIcon" params="{url:'<?=$this->url(array('module'=>'admin','controller'=>'user','action'=>'delete','format'=>'json'))?>',item:'<?=$user->id?>'}"></span><img class="loader" src="/images/ajax-loader1.gif"></td>
			</tr>
		<?php endforeach;?>
	</table>
	</div>
	<div id="rightContentContainer">
		<div id="rightContent">
			<div id="searchForm">
				<div id="searchFormContent">
					<?=$this->formSearch?>
				</div>
			</div>
		</div>
	</div>
</div>
