<?php
$user = $this->user;
$arr_address = array(
	'address'		=>	$user->address,
	'subdistrict'	=>	$user->subdistrict,
	'district'		=>	$user->district,
	'province_code'		=>	$user->province_code,
	'zipcode'		=>	$user->zipcode
);
$phones = array('home'=>$user->telephone, 'mobile'=>$user->mobilephone);

$user_info = array(
				array(
					'label'	=>	'หมายเลขสมาชิก',
					'value'	=>	$user['id'],
					'readonly'	=>	true,
				),
				array(
					'label'	=>	'วันที่สมัคร',
					'value'	=>	$user['created_date'],
					'readonly'	=>	true,
				),
				array(
					'label'	=>	'ชื่อ-สกุล',
					'value'	=>	$user['first_name'] . ' ' . $user['last_name'],
					'editor'=>	'name',
				),
				array(
					'label'	=>	'นามแฝง',
					'value'	=>	$user['alias'],
					'editor'=>	'alias',
				),
				array(
					'label'	=>	'เพศ',
					'value'	=>	$this->gender($user['gender']),
					'editor'=>	'gender',
				),
				array(
					'label'	=>	'วันเกิด',
					'value'	=>	$user['birthday'],
					'editor'=>	'birthday',
				),
			array(
					'label'	=>	'ที่อยุ่ปัจจุบัน',
					'value'	=>	$this->address($arr_address),
					'editor'=>	'address',
				),
			array(
				'label'	=>	'เบอร์โทรศัพท์',
				'value'	=>	$this->phonenumber($phones),
				'editor'=>	'phone',
				),
			array(
					'label'	=>	'อีเมล์',
					'value'	=>	$user['email'],
					'editor'=>	'email',
				),
			array(
					'label'	=>	'รหัสผ่าน',
					'value'	=>	'ข้อมูลลับ',
					'nodata'=>	true,
					'editor'=>	'password',
				),
			array(
					'label'	=>	'บทบาท',
					'value'	=>	$this->user->role->name,
					'editor'=>	'role',
				),
);
?>

<div id="infoSettings">
		<ul class="viewList">
			<?php foreach ($user_info as $user_field):?>
				<li class="viewListItem" ajaxurl="/admin/user/editor/name/<?=$user_field['editor']?>" itemId="<?=$this->user->id?>")">
					<div <?=(!$user_field['readonly']) ? 'class="title"' : null?>>
						<span class="label"><?=$user_field['label']?></span>
							<span class="value <?=(($user_field['nodata'])?'noData':null)?>">
								<?=$user_field['value']?>
							</span>
						<?php if (!$user_field['readonly']):?>
						<img class="loader" src="/images/ajax-loader1.gif" alt="loader" width="16px" height="16px" class="hidden">
						<span class="edit icon color1C92B7 editIcon"></span>
						<?php endif;?>
					</div>
					<div class="editor"></div>
				</li>
			<?php endforeach;?>
		</ul>
</div>