<?php echo $this->doctype() ?>
<html>
<head>
<?php echo $this->headMeta() ?>
<?php echo $this->headTitle() ?>
<?php echo $this->headLink()
		->appendStylesheet('/css/admin.css')
		->appendStylesheet('/css/silver-theme.css'); ?>
<?php echo $this->headScript() ?>
<?php
/*Setup Dojo*/
if ($this->dojo()->isEnabled()) {
	/*
	 * Dojo initialization
	 */
	$this->dojo()	->setDjConfig(array(
						//'JSONPlain'	=>	true,
						'parseOnLoad'	=>	true,
						//'isDebug'		=>	true,
						//'locale'	=>	$this->layout()->locale->getLanguage(),
					))
					->addStylesheetModule('dijit.themes.tundra')
					/*
					 * Local
					 */
					->setLocalPath('/js/libs/dojo/1.7.1/dojo/dojo.js');
					//->setLocalPath('http://ajax.googleapis.com/ajax/libs/dojo/1.7.1/dojo/dojo.js');
					/*
					 * Cloud
					 *
					->setCdnBase(Zend_Dojo::CDN_BASE_GOOGLE)
					->setCdnDojoPath(Zend_Dojo::CDN_DOJO_PATH_GOOGLE)
					->setCdnVersion('1.7.1')
					->useCdn();*/
	echo $this->dojo();
	echo '<style>.tundra .dijitDialogUnderlay { background:#000; };</style>';
}
?>
</head>
<body class="tundra">
<div class="globalContainer">
	<div class="pageContainer">
		<div class="headerContainer">
			<div id="mainMenu">
				<ul class="menu mainMenu">
					<li class="menuItem mainMenuItem"><img src="/images/main_menu_left.png" style="cursor:pointer"></a></li>
					<li class="menuItem mainMenuItem"><a href="#">จัดการคำสั่งซื้อ</a></li>
					<li class="menuItem mainMenuItem"><a href="<?=$this->url(array('controller'=>'product','action'=>'index'))?>">จัดการสินค้า</a></li>
					<li class="menuItem mainMenuItem"><a href="<?=$this->url(array('controller'=>'user','action'=>'index'))?>">จัดการผู้ใช้</a></li>
					<li class="menuItem mainMenuItem"><a href="#">จัดการเนื้อหา</a></li>
					<li class="menuItem mainMenuItem"><a href="#">จดหมายข่าว</a></li>
					<li class="menuItem mainMenuItem"><a href="#" style="background-image:none; margin-right:31px">ตั้งค่าการใช้งานอื่นๆ</a></li>
					<li class="menuItem mainMenuItem"><img src="/images/main_menu_right.png"></li>
				</ul>
			</div>
		</div>
		<div class="contentContainer">
			<div class="mainContent">
				<?php echo $this->layout()->content; ?>
			</div>
		</div>
		<div class="footerContainer">
			footer here!
		</div>
 	</div>
</div>
</body>
</html>
