<?php 
$this->dojo()
	->requireModule(array(
		'dijit.form.Form',
		'dijit.form.TextBox',
		'dijit.form.ValidationTextBox',
		'dijit.form.Select',
		'dijit.form.FilteringSelect',
		'dijit.Editor',
		'dijit.form.CurrencyTextBox',
		'dijit.form.Button',
		'dijit.form.RadioButton',
		'dojox.form.BusyButton',
		'dojo.NodeList-traverse',
	));
$this->dojo()->onLoadCaptureStart();
?>
function(){
	var nodes = dojo.query('a.listItemOperation');
	nodes.connect('onclick','deleteListItem');
}
<?php $this->dojo()->onLoadCaptureEnd();?>
<div id="leftContent">
	<div id="leftMenuTitle">
		<span class="label">จัดการเนื้อหา</span>
		<span class="icon colorE9E9E9 editIcon"></span>
	</div>
	<div id="leftMenu">
		<?php echo $this->navigation()->menu(); ?>
	</div>
</div>

<div id="centerContentContainer">
	<div id="centerContent">
	<?php
	//use dojo dialog
	echo $this->customDijit('Dialog',null,array(
			'dojoType'	=>	'dijit.Dialog',)
	);

	?>
	<div id="searchResultLabel">ผลการค้นหาพบทั้งหมด <?=Zend_Locale_Format::toNumber($this->contents->count())?> รายการ</div>
	<table class="resultTableList">
		<tr>
			<th style="width:100px">รหัสเนื้อหา</th>
			<th>หัวข้อ</th>
			<th>หมวด</th>
		</tr>
		<?php foreach ($this->contents as $content):?>
			<tr class="resultTableListItem" onclick="openDialog('รายละเอียดเนื้อหา','/admin/content/view/item/<?=$content->id?>')">
				<td><?=$content->id?></td>
				<td><?=$content->name?></td>
				<td><?=$content->category->name?><a href="#" class="listItemOperation icon colorE9E9E9 closeIcon" ajaxurl="<?=$this->url(array('module'=>'admin','controller'=>'content','action'=>'delete'))?>" itemId="<?=$content->id?>"></a></td>
			</tr>
		<?php endforeach;?>
	</table>
	</div>
	<div id="rightContentContainer">
		<div id="rightContent">
			<div id="searchForm">
				<div id="searchFormContent">
					<?=$this->formSearch?>
				</div>
			</div>
		</div>
	</div>
</div>