<?php
$date = new Zend_Date();
$product = $this->product;
$thumbHelper = $this->thumbnail();
$thumbUrl = $thumbHelper->url(array('group'	=>	'products','iid'	=>	$product->id,'size'	=>	'small',));

$rows = array(
				array(
					'label'	=>	'รหัสสินค้า',
					'value'	=>	$product->id,
					'readonly'	=>	true,
				),
				array(
					'label'	=>	'หมวดสินค้า',
					'value'	=>	$product->categoryName,
					'field'=>	'category',
				),
				array(
					'label'	=>	'ชื่อสินค้า',
					'value'	=>	$product->name,
					'field'=>	'name',
				),
				array(
					'label'	=>	'รูปสินค้า',
					'value'	=>	( ($thumbHelper->isExist($thumbUrl))?'<img src="'. $thumbUrl . '?' . time() . '" style="margin-top:10px;">':null ),
					'field'=>	'thumbnail',
				),
				array(
					'label'	=>	'รายละเอียด',
					'value'	=>	$product->description,
					'field'=>	'description',
				),
				array(
					'label'	=>	'ราคาขาย',
					'value'	=>	Zend_Registry::get('Zend_Currency')->toCurrency($product->price),
					'field'=>	'price',
				),
);

echo $this->partial('viewlist-partial.phtml',array('rows'=>$rows,'item'=>$product->id));
?>