<div id="loginContainer">
	<form id="<?=$this->element->getId()?>" action="<?=$this->element->getAction()?>" method="<?=$this->element->getMethod()?>" onsubmit="processLogin()">	
		<dl>
			<dt></dt>
			<dd class="smallSizeText"><a href="<?=$this->url(array('action'=>'add','controller'=>'user-index','module'=>'auth'),null,true)?>">สมัครสมาชิกใหม่</a> | <a href="">ลืมรหัสผ่าน</a></dd>
			<?=$this->element->identity?>
			<?=$this->element->password?>
			<dt></dt>
			<dd><?=$this->formSubmit($this->element->login->getName(),$this->element->login->getLabel())?> <span class="responseMessage"></span></dd>
		</dl>
	</form>
</div>