<div class="articleContainer">
	<?php foreach ($this->articles as $article):?>
	<?php $viewUrl = $this->url(array('action'=>'view','id'=>$article->rowid))?>
	<div class="article">
		<a href="<?=$viewUrl?>"><img src="<?=$this->thumbnail()->url(array('group'=>'contents','cid'=>$article->category_id,'iid'=>$article->id,'size'=>'medium'))?>" width="249px" height="178px"></a>
		<div class="meta">
			<a href="<?=$viewUrl?>"><h2><?=$article->name?></h2></a>
			<div class="description"><?=$article->description?></div>
			<div class="stat">
				<span class="viewStat" title="อ่าน">12</span><span class="commentStat" title="แสดงความคิดเห็น">101</span>
			</div>
		</div>
	</div>
	<?php endforeach;?>
</div>