<?php

/**
 * Role
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Role extends Model_BaseRole
{
    const USER_MEMBER = 1;
    const USER_ADMIN = 2;
    
	public function setUp(){
		parent::setUp();
		
		$this->hasMany('Model_User as users',array(
			'local'		=>	'id',
			'foreign'	=>	'role_id',
		));
	}
	
	public function createQuery($alias)
	{
		$q = $this->getTable()->createQuery($alias);
		return $q;
	}
	
}