<?php

/**
 * Content
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Content extends Model_BaseContent
{
    public function setUp()
    {
        parent::setUp();
        
    	$this->hasOne('ContentCategory as category',array(
			'local'		=>	'category_id',
			'foreign'	=>	'id',
		));
    	
    	$this->hasOne('User as createdBy',array(
    			'local'		=>	'created_by_id',
    			'foreign'	=>	'id',
    	));
    }

    public static function getInstance(){
    	static $_table = null;
    	if(null==$_table){
    		$class = __CLASS__;
    		$_table = new $class();
    	}
    	return $_table;
    }
    
    /**
     *
     * Return lastest content by category in limitation
     *
     * @param int $categoryId
     * @param int $limit
     * @param int $hydrationMode
     *
     * @return mixed
     */
    public function findLastByCategory($categoryId,$limit,$hydrationMode=null){
    	$q = $this->createQuery('c');
    	$q	->addWhere('c.category_id = ?', $categoryId)
    	->addOrderBy('c.id DESC')
    	->limit($limit);
    	return $q->execute(array(),$hydrationMode);
    }
}