<?php

/**
 * ContentCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_ContentCategory extends Model_BaseContentCategory
{
	public function setUp()
	{
	    parent::setUp();
	    
	    $this->hasMany('Content as contents',array(
	    		'local'		=>	'id',
	    		'foreign'	=>	'category_id',
	    ));
	}
	
	public static function getInstance(){
		static $_table = null;
		if(null==$_table){
			$class = __CLASS__;
			$_table = new $class();
		}
		return $_table;
	}
}