<?php

/**
 * Product
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_Product extends Model_BaseProduct
{
	public function setUp(){
		parent::setUp();
		
		$this->hasOne('ProductCategory as category',array(
			'local'		=>	'category_id',
			'foreign'	=>	'id',
		));
	}
	
	public static function getInstance(){
		static $_table = null;
		if(null==$_table){
		    $class = __CLASS__;
			$_table = new $class();
		}
		return $_table;
	}

	/**
	 * 
	 * Return lastest product by category in limitation
	 * 
	 * @param int $categoryId
	 * @param int $limit
	 * @param int $hydrationMode
	 * 
	 * @return mixed
	 */
	public function findLastByCategory($categoryId,$limit=null,$hydrationMode=null){
		$q = $this->createQuery('p');
	    $q	->addWhere('p.category_id = ?', $categoryId)
	    	->addOrderBy('p.id DESC');
	    if(!empty($limit)) {
	        $q	->limit($limit);
	    }
	    	
		return $q->execute(array(),$hydrationMode);
	}
	/**
	 *
	 * @param string $value
	 *
	 * @return Model_Product
	 */
	public function findOneByCode($code){
		$array = explode('-',$code);
		$id = $array[count($array)-1];
		if ($array) {
		    return $this->findOneById($id);
		}
		return false;
	}
	/**
	 * Return current product price
	 * @return integer
	 */
	public function getPrice(){
	    if (!empty($this->sale_price)) {
	        return $this->sale_price;
	    }
	    return $this->normal_price;
	}
	
}