<?php

/**
 * PurchaseOrderStatus
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_PurchaseOrderStatus extends Model_BasePurchaseOrderStatus
{
    public function setUp()
    {
    	parent::setUp();
    	
    	$this->hasMany('Model_PurchaseOrder as orders',array(
    			'local'		=>	'id',
    			'foreign'	=>	'status_id',
    	));
    
    }
    
    public function createQuery($alias)
    {
    	$q = $this->getTable()->createQuery($alias);
    	return $q;
    }
}