<?php

/**
 * ArticleCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * @property Doctrine_Collection() articles
 * 
 * @package    ##PACKAGE##
 * @subpackage ##SUBPACKAGE##
 * @author     ##NAME## <##EMAIL##>
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Model_ArticleCategory extends Model_BaseArticleCategory
{
	public function setUp()
	{
	    parent::setUp();
	    
	    $this->hasMany('Model_Article as articles',array(
	    	'local'		=>	'id',
	    	'foreign'	=>	'category_id',
	    ));
	}
	
	public function createQuery($alias)
	{
		$q = $this->getTable()->createQuery($alias);
		return $q;
	}
}